/**
 * 設定管理の型定義
 */

import type { AppSettings } from './common';

export interface SettingField {
  key: string;
  label: string;
  description?: string;
  type: 'text' | 'number' | 'boolean' | 'select' | 'color' | 'date' | 'time';
  value: any;
  defaultValue: any;
  required?: boolean;
  disabled?: boolean;
  validation?: SettingValidation;
  options?: SettingOption[]; // For select type
  group?: string;
  order?: number;
}

export interface SettingOption {
  value: any;
  label: string;
  description?: string;
  disabled?: boolean;
}

export interface SettingValidation {
  min?: number;
  max?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  custom?: (value: any) => string | null; // Returns error message or null if valid
}

export interface SettingGroup {
  key: string;
  label: string;
  description?: string;
  icon?: string;
  order?: number;
  fields: SettingField[];
}

export interface SettingsConfig {
  groups: SettingGroup[];
  version: string;
  lastUpdated: Date;
}

export interface SettingsState {
  config: SettingsConfig;
  currentValues: Record<string, any>;
  originalValues: Record<string, any>;
  isDirty: boolean;
  isLoading: boolean;
  isSaving: boolean;
  errors: Record<string, string>;
  lastSaved?: Date;
}

export interface SettingsFormProps {
  groups: SettingGroup[];
  values: Record<string, any>;
  errors?: Record<string, string>;
  disabled?: boolean;
  onFieldChange: (key: string, value: any) => void;
  onValidate?: (key: string, value: any) => string | null;
}

export interface SettingsPageState {
  activeGroup?: string;
  showResetDialog: boolean;
  showUnsavedChangesDialog: boolean;
}

// 施設固有の設定項目
export interface FacilitySettings extends AppSettings {
  facility: {
    name: string;
    address: string;
    phone: string;
    email: string;
    license: string;
    capacity: number;
  };
  dashboard: {
    defaultCards: string[];
    allowCustomization: boolean;
    refreshInterval: number; // seconds
    maxCardsPerUser: number;
  };
  users: {
    autoArchiveInactive: boolean;
    inactiveThresholdDays: number;
    requirePhotoUpload: boolean;
    allowFamilyAccess: boolean;
  };
  staff: {
    requireApprovalForUpdates: boolean;
    enableScheduleManagement: boolean;
    maxWorkHoursPerWeek: number;
    overtimeThreshold: number;
  };
  reports: {
    autoGenerateDaily: boolean;
    requireApprovalBeforeSending: boolean;
    defaultTemplate: string;
    retentionPeriodDays: number;
  };
  chat: {
    enableFileAttachments: boolean;
    maxFileSize: number; // MB
    allowedFileTypes: string[];
    messageRetentionDays: number;
  };
  security: {
    sessionTimeoutMinutes: number;
    requireTwoFactor: boolean;
    passwordMinLength: number;
    passwordRequireSpecialChars: boolean;
    maxLoginAttempts: number;
    lockoutDurationMinutes: number;
  };
}

export type SettingFieldType = SettingField['type'];
export type SettingValue = string | number | boolean | Date;